### ISSUE TITLE
install_windows_updates.ps1 dropbox file

### ISSUE THREAD

**Issue by pitermarx** [MattHodge/PackerTemplates#1]
is the https://dl.dropboxusercontent.com/u/727435/Tools/WUInstallAMD64.exe from your dropbox ? 
should this be something else like nuget

**Comment by MattHodge** [comment]
@pitermarx please feel free to turn it into a Chocolatey package, then I will switch over to using it.

The reason for storing in dropbox is that the company doesn't allow you to download the tool from their website without providing an email address, which I cannot do via PowerShell (https://www.wuinstall.com/)
