### ISSUE TITLE
Ability to Selectively apply updates

### ISSUE THREAD

**Issue by johnrizzo1** [MattHodge/PackerTemplates#14]
Right now you are not to be able to build an identical image to what was created at any point in the past.  For example.  If on January first Microsoft had released patch1, patch2 and patch3 and you build a Windows 2016 image, which applies those updates, and then on February first you try to rebuild that image you will end up with an image that has all of the updates that were originally applied but all of the subsequent updates as well.

It would be great to be able to easily support this so we can build repeatable images at any point in time.

**Comment by MattHodge** [comment]
The method I am using to install Windows Updates (WUInstall) has a switch allowing this regarding this called `/releasedate`

Documentation here: http://help.wuinstall.com/en/WuInstall.html?FilterOptions.html

You can customize it yourself using the `install_windows_updates.ps1` script.

I will not be supporting it as an option in this repo though.
