### ISSUE TITLE
Windows 2016 Dataceneter Core

### ISSUE THREAD

**Issue by stephenbawks** [MattHodge/PackerTemplates#2]
Is there a way I can build Windows 2016 Datacenter Core instances.  I am guessing I just need to add the extra condition for Datacenter but i am not sure where you are pulling the os_name value from.

**Comment by SolidOceanTrust** [comment]
Hello gigadafud.
If you mount the ISO for Server 2016 and then run the following command: (assuming G: is the drive letter for your ISO)
**Get-WindowsImage -ImagePath g:\sources\install.wim**

You will see both the NAMES and INDEX's for the image.

I would make an additional folder in /answer_files for win2016datacentercore
in that folder, copy the unattend.xml from the /answer_files/win2016std or /answer_files/win2016stdcore to the win2016datacentercore and modify then XML section called ImageInstall/OSImage/Installrom 
/IMAGE/NAME
Windows Server 2016 SERVERDATACENTERCORE

Hope that helps!

**Comment by MattHodge** [comment]
Thanks for the answer @SolidOceanTrust  :)

**Comment by stephenbawks** [comment]
Yes it does.  Trying that out now.  Thank you very much.  Was just coming
up blank on where those Image Names were being pulled from.

Thanks again.



On Sat, Feb 25, 2017 at 4:24 PM, Solid Ocean Trust <notifications@github.com
