### ISSUE TITLE
install_oracle_guest_additions.ps1 file name not found

### ISSUE THREAD

**Issue by SolidOceanTrust** [MattHodge/PackerTemplates#3]
When I cloned the repo and tried to get the virtualbox guest additions installed, the script (packer) said that it could not find the file E:\cert\oracle-vbox.cer.
I am using Virtual Box version 5.1.143112924.

I fixed the script to add the correct certs by their new names and will be submitting a pull request to that effect.

Thank you Matt for this is AWESOME repo/project.

**Comment by MattHodge** [comment]
Sounds good :D look forward to it

**Comment by MattHodge** [comment]
Will discuss this change in PR #4
