### ISSUE TITLE
VRam for virtualbox?

### ISSUE THREAD

**Issue by TraGicCode** [MattHodge/PackerTemplates#8]
Why do you configure video memory for virtualbox?  Does this speed up provisioning?

**Comment by MattHodge** [comment]
No real reason I can think of.. but it's in and it works so going to leave it :P

**Comment by TraGicCode** [comment]
Never posted back but I believe you did the vram stuff in packer templates so you can maximize virtualbox windows so you can go full screen and not be stuck in a super small vm windows
