### ISSUE TITLE
Taking PRs?

### ISSUE THREAD

**Issue by petemounce** [MattHodge/PackerTemplates#9]
I forked, and would like to contribute back:
* output directories as variables - I build to an external drive where I have more space
* some moving of things around so attributes are all ordered the same way and things like that, to make edits easier to place
* a different way of doing windows updates, because the current one relies on a binary in a dropbox that now 404s
  * I was thinking to either steal the code of [Ansible's win_updates module](https://docs.ansible.com/ansible/win_updates_module.html), or [`choco install pswindowsupdate`](https://chocolatey.org/packages/pswindowsupdate) which I've used successfully in the past.

What do you think?

Also - I like the build chain of templates - is there a way to get cake to realise that it doesn't need to rebuild a dependency, but instead build incrementally? I'm unfamiliar.

**Comment by ghost** [comment]
Sounds awesome! Bring em on!

**Comment by petemounce** [comment]
Wonderful!

**Comment by petemounce** [comment]
Also #11

**Comment by MattHodge** [comment]
Hi @petemounce .

Please make smaller PR's and test them out.

It's hard for me to run through 100's of lines of changes and then find them not to work - takes a lot of time.
